/**
 * Wiki type definitions for jelly_code.
 *
 * Aligns with the LLM-Wiki design spec §3:
 * - Source: raw document compilation result
 * - Entity: extracted knowledge entity (concept/project/service/api)
 * - Topic: synthesized cross-entity analysis
 * - LogEntry: audit trail for wiki operations
 *
 * NOTE: All wiki node types carry `projectId` for multi-tenant isolation,
 * matching the same pattern used by CodeNode. This fixes ISSUE-002 where
 * cross-project wiki data was being MERGEd together.
 */

import type { CodeSignature } from './code-signature.js';

// Entity types
export type EntityType = 'concept' | 'project' | 'service' | 'api';

// Source page — compiled from a raw document
export interface WikiSource {
  id: string;              // "source-{key}"
  projectId: string;       // ⬅ multi-tenant isolation key (ISSUE-002)
  title: string;
  sourcePath: string;      // "raw/specs/xxx.md"
  summary: string;
  keyPoints: string[];
  compiledAt: string;      // ISO datetime
  /** SHA-256 hash of the source file content (P2 idempotency — skip LLM if unchanged) */
  contentHash?: string;
  /** SHA-256 hash of the last LLM compile output (P2 idempotency — skip write if unchanged) */
  llmOutputHash?: string;
}

// Entity page — extracted knowledge entity
export interface WikiEntity {
  id: string;              // "{entity-name}" (kebab-case)
  projectId: string;       // ⬅ multi-tenant isolation key (ISSUE-002)
  name: string;
  entityType: EntityType;
  definition: string;
  details: string;
  firstCompiled: string;   // ISO datetime
  lastUpdated: string;     // ISO datetime
  /**
   * Code signature binding for staleness detection (P0c).
   *
   * - When set: the entity is "bound" to a code entity; staleness can be
   *   detected by comparing signatureHash/astHash to the current source.
   * - When `null`: the entity has been explicitly marked as unbound
   *   (e.g. a concept page that intentionally has no code counterpart).
   * - When `undefined`: the entity predates P0c and has not yet been
   *   bound. This is the backward-compat default — old data loads cleanly.
   */
  codeSignature?: CodeSignature | null;
  /**
   * Bitemporal start (P1): the time from which this entity version is
   * considered valid. When omitted, the entity is valid from firstCompiled.
   */
  validFrom?: string;      // ISO datetime
  /**
   * Bitemporal end (P1): the time until which this entity version is
   * considered valid. When omitted, the entity is still current.
   */
  validTo?: string;        // ISO datetime
  /**
   * Provenance (v1.3.0 Phase 1 T1-1): tracks the origin of this entity.
   *
   * - 'auto-derived': generated by auto-derive from code graph (Phase 3)
   * - 'manual': created via ingest/batchIngest by a human or agent
   * - 'human-verified': reviewed and confirmed by a human
   * - `undefined`: predates v1.3.0, backward-compatible default
   *
   * Used by delete-orphaned (Phase 2) and undo-auto-derived (Phase 2)
   * to distinguish safely-removable auto entities from manually-curated ones.
   */
  provenance?: 'auto-derived' | 'manual' | 'human-verified';
  /**
   * ISO datetime when auto-derive produced this entity.
   * Only set when `provenance === 'auto-derived'`.
   */
  derivedAt?: string;      // ISO datetime
}

// Topic page — synthesized cross-entity analysis
export interface WikiTopic {
  id: string;              // "topic-{key}"
  projectId: string;       // ⬅ multi-tenant isolation key (ISSUE-002)
  title: string;
  content: string;
  compiledAt: string;      // ISO datetime
  /**
   * P2-T4: Topic type discriminator.
   *
   * - 'general': regular wiki query write-back (default for backward compat).
   *   Used by WikiService.query() when saving Q&A topics.
   * - 'evolution': code evolution story generated by generateEvolutionStory().
   *   Contains an LLM narrative about a code symbol's history.
   *
   * When omitted, consumers should default to 'general'.
   */
  topicType?: 'general' | 'evolution';
}

// Log entry — audit trail
export interface WikiLogEntry {
  id: string;
  projectId: string;       // ⬅ multi-tenant isolation key (ISSUE-002)
  action: 'ingest' | 'batch_ingest' | 'batch_ingest_content' | 'query' | 'lint' | 'sync' | 'reindex';
  description: string;
  details: string;
  pageCount: number;
  createdAt: string;       // ISO datetime
}

// Extracted entity from LLM compile output
export interface ExtractedEntity {
  name: string;
  type: EntityType;
  definition: string;
  details: string;
  links: Array<{ target: string; relationship: string }>;
}

// Update to an existing entity
export interface ExistingUpdate {
  entityName: string;
  newInfo: string;
  sourceSection: string;
}

// Contradiction detected during compile
export interface Contradiction {
  entityName: string;
  description: string;
}

// LLM compile output structure
export interface CompileOutput {
  title: string;
  summary: string;
  keyPoints: string[];
  entities: ExtractedEntity[];
  existingUpdates: ExistingUpdate[];
  contradictions: Contradiction[];
}

// Single ingest result
export interface IngestResult {
  source: WikiSource;
  entitiesCreated: number;
  entitiesUpdated: number;
  contradictions: number;
  /** true when the file content was unchanged and LLM was skipped (P2 idempotency) */
  skipped?: boolean;
}

// Batch ingest result
export interface BatchIngestResult {
  results: IngestResult[];
  totalCompiled: number;
  errors: Array<{ path: string; error: string }>;
}

// Wiki status (raw file compilation status)
export interface WikiStatus {
  compiled: Array<{ path: string; sourceId: string; compiledAt: string }>;
  uncompiled: Array<{ path: string }>;
  total: number;
}

// Wiki index (knowledge map)
export interface WikiIndex {
  entities: Array<{ id: string; name: string; type: EntityType; linkCount: number }>;
  sources: Array<{ id: string; title: string; entityCount: number }>;
  topics: Array<{ id: string; title: string }>;
}

// Wiki search document for Typesense + Qdrant
export interface WikiPageDoc {
  id: string;
  projectId: string;       // ⬅ retained for search-result routing (ISSUE-002)
  pageType: 'source' | 'entity' | 'topic';
  title: string;
  content: string;
  entityType?: string;
  compiledAt: number;  // Unix timestamp
}

/**
 * Result of a wiki lint check.
 *
 * Moved here from service.ts (P0c-T2) for consistency with other wiki
 * type definitions. The `type` union is extended with `'unbound'` to
 * flag entities that lack a code signature binding.
 */
export interface LintIssue {
  type: 'orphan' | 'missing_ref' | 'stale' | 'contradiction' | 'unbound';
  entityId: string;
  entityName?: string;
  description: string;
  severity: 'warning' | 'error';
}
